### ISSUE TITLE
License

### ISSUE THREAD

**Issue by AxelTerizaki** [KuroSensei/anime-karaokes-ass#1]
Buenos dias.

¡Gracias por crear este repositorio github!

Tengo una pregunta sobre la licencia GPLv3. Esta licencia es más adecuada para software que para contenido artístico como karaoke. Aquí está la página de Wikipedia de la licencia: https://es.wikipedia.org/wiki/Creative_Commons

¡Gracias nuevamente por su trabajo y por hacer que todo esto esté disponible!

**Comment by MarceloTLD** [comment]
Pues tienes mucha razón, la verdad no pensé mucho cuando agregué la licencia. Simplemente puse la que pensé sería la más adecuada. Ahora mismo corrijo eso.
